# COLORS (R,G,B)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BROWN = (85,35,0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)
LIGHTGREY2 = (176,176,176)
LIGHTGREY2_ALPHA = (255,255,255, 75)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
COLOR_INACTIVE = (40, 40, 40)
COLOR_ACTIVE = (176,176,176)
TEXT_BLUE = (137,194,212)
TEXT_DARK_BLUE = (25,75,184)

# GAME SETTINGS
WIDTH = 1024
HEIGHT = 768
FPS = 60
TITLE = "Em busca do Pinico"
BGCOLOR = DARKGREY


#PLAYER SETTINGS
PLAYER_IMG_UP1 = 'char_02 (12).png' # STOP
PLAYER_IMG_UP2 = 'char_02 (1).png'
PLAYER_IMG_UP3 = 'char_02 (11).png'
PLAYER_IMG_RIGHT1 = 'char_02 (9).png' # STOP
PLAYER_IMG_RIGHT2 = 'char_02 (8).png'
PLAYER_IMG_RIGHT3 = 'char_02 (10).png'
PLAYER_IMG_LEFT1 = 'char_02 (6).png' # STOP
PLAYER_IMG_LEFT2 = 'char_02 (5).png'
PLAYER_IMG_LEFT3 = 'char_02 (7).png'
PLAYER_IMG_DOWN1 = 'char_02 (3).png' # STOP
PLAYER_IMG_DOWN2 = 'char_02 (2).png'
PLAYER_IMG_DOWN3 = 'char_02 (4).png'
PLAYER_STEPS = 3

#PLAYER MOVEMENT
PLAYER_TIME_WAIT = 80

#PLAYER SCORES
ANDAR_SCORE = 10
ANDAR_COM_LOOP_SCORE = 20
LAVAR_MAOS_SCORE = 30
SECAR_MAOS_SCORE = 50
ABRIR_TORNEIRA_SCORE = 30
FECHAR_TORNEIRA_SCORE = 30
DAR_DESCARGA_SCORE = 30
USAR_PAPEL_SCORE = 30
ABAIXAR_CALCAS_SCORE = 30
LEVANTAR_CALCAS_SCORE = 30
ABRIR_TAMPA_SCORE = 30
FECHAR_TAMPA_SCORE = 50

#MAP SETTINGS
MAP_SHIFT_X = 424
MAP_SHIFT_Y = 84
TILESIZE = 24
GRIDWIDTH = WIDTH / TILESIZE
GRIDHEIGHT = HEIGHT / TILESIZE

#PLAYER ACTION OBJECTS
LAVAR_MAOS = 'sink_action'
ABRIR_TORNEIRA_ACTION = 'sink_action'
FECHAR_TORNEIRA_ACTION = 'sink_action'

SECAR_MAOS = 'towel_action'

DAR_DESCARGA = 'vaso_action'
ABAIXAR_CALCAS_ACTION = 'vaso_action'
LEVANTAR_CALCAS_ACTION = 'vaso_action'
ABRIR_TAMPA_ACTION = 'vaso_action'
FECHAR_TAMPA_ACTION = 'vaso_action'

USAR_PAPEL = 'papel'

# DESENTUPIR = 'desentupidor'

TOMAR_BANHO = 'shower_action' # AINDA NÃO IMPLEMENTADO


# ACTION IMAGENS
MOVER_CIMA = 'up-arrow.png'
MOVER_BAIXO = 'down-arrow.png'
MOVER_DIREITA = 'right-arrow.png'
MOVER_ESQUERDA = 'left-arrow.png'
ABRIR_TORNEIRA = 'abrir_torneira.png'
FECHAR_TORNEIRA = 'fechar_torneira.png'
ABRIR_TAMPA = 'tampa_aberta.png'
DESCARGA = 'descarga.png'
FECHAR_TAMPA = 'tampa_fechada.png'
# DESENTUPIDOR = 'desentupidor.png'
LAVAR_MAOS_ACTION = 'lavar_maos.png'
SECAR_MAOS_ACTION = 'secar_maos.png'
LOOP = 'loop.png'
PAPEL_ACTION = 'papel.png'
PANTS_DOWN = 'pants_down.png'
PANTS_UP = 'pants_up.png'
PAUSE = 'pause-button.png'
PLAY = 'play-button.png'
RESET = 'reload-button.png'

#ACTION INDEX

MOVER_CIMA_IND = 0
MOVER_BAIXO_IND = 1
MOVER_DIREITA_IND = 2
MOVER_ESQUERDA_IND = 3
LOOP_IND = 4
ABRIR_TORNEIRA_IND = 5
FECHAR_TORNEIRA_IND = 6
ABRIR_TAMPA_IND = 7
DAR_DESCARGA_IND = 8
FECHAR_TAMPA_IND = 9
# DESENTUPIDOR_IND = 10
LAVAR_MAOS_ACTION_IND = 10
SECAR_MAOS_ACTION_IND = 11
PAPEL_ACTION_IND = 12
PANTS_DOWN_IND = 13
PANTS_UP_IND = 14
PAUSE_IND = 15
PLAY_IND = 16
RESET_IND = 17



#UI

## UI POP UPS
UI_N_LOOP_UNSEL = 0
UI_N_LOOP_SEL = 1
UI_MSG_BOX_IND = 2
UI_PLAYER_BLOCKED_IND = 3



## UI CURSOR
CURSOR_GRAB = 'cursor_hand.png'
CURSOR = 'cursor_pointerFlat.png'

## UI POPUP CONFIGS
UI_N_LOOP_UNSEL_IMG = 'UI_repet_loop_unsel.png'
UI_N_LOOP_SEL_IMG = 'UI_repet_loop_sel.png'

UI_MSG_BOX = 'msg_box.png'

UI_PLAYER_BLOCKED = 'blocked.png'

UI_PENDENTE = 'pendente.png'
UI_DONE = 'done.png'

UI_WINNER = 'winner.png'
UI_LOST = 'lost.png'

UI_RECT_ACTION_IMG = 'rect_movement.png'
UI_RECT_CHOOSER_IMG = 'rect_chooser.png'


## UI ANIMATIONS
UI_ANIM_BOX = 'anim_box.png'
UI_BOX_NOT_ALLOWED = 'box_not_allowed.png'

NOT_ALLOWED_ANIM_DELAY = 150
GAME_OVER_DELAY = 300
WINNER_DELAY = 500


BLOCKED_DELAY = 8


## UI ANIMATIONS INDEX
UI_ANIM_BOX_IND = 0
UI_BOX_NOT_ALLOWED_IND = 1

# UI FONT

UI_FONT = 'Vinegar Stroke.ttf'

#UI EXECUTION
RADIUS = 24
